### ISSUE TITLE
Request keep multiple versions

### ISSUE THREAD

**Issue by ksurl** [aysiu/OldMunkiPackages#19]
possibly store the setting as a value in the plist?

**Comment by aysiu** [comment]
I'll have to think about this, because this would be a major overhaul of how the logic works currently. Right now, there's basically a dictionary of all the items, and if the item is already in there, it's considered redundant, and the newer one is kept.

To keep multiple past versions _en masse_ (i.e., not for a specific item) would be not just a small tweak but an entirely different approach to the logic.

I was going to suggest *repoclean* (which Greg Neagle created after I'd already made OldMunkiPackages), but it follows the same logic (clean out everything, unless you specify specific items to keep multiple versions of:
```
repoclean --help
Usage: repoclean [options] [/path/to/repo_root]

Options:
  -h, --help            show this help message and exit
  -V, --version         Print the version of the munki tools and exit.
  -k KEEP, --keep=KEEP  Keep this many versions of a specific variation.
                        Defaults to 2.
  --show-all            Show all items even if none will be deleted.
  --delete-items-in-no-manifests
                        Also delete items that are not referenced in any
                        manifests. Not yet implemented.
```

**Comment by aysiu** [comment]
@ksurl

Also, before I start even thinking about working on this, can you explain a bit more what the use case would be for keeping multiple versions of _every_ item, instead of just particular protected items?

There are already a few areas of flexibility in place—items won't get removed if they are not matching sets of catalogs, items won't get removed if they're in the protected packages dictionary, and items won't get removed if they have different minimum OS requirements.

Just so you know, when I run this script, it dumps my old items into an old items folder (not the trash), and I sometimes (rarely) have occasion to dump an old item back into the repo, but I don't see the need to keep multiple versions of _every_ item.

I'm just trying to get a sense of how heavily I should invest in rewriting code for something that doesn't make sense to me. Or maybe you might make a strong case for how to approach maintaining a repo, and I might think "Oh, that's an interesting point... maybe I should do that, too."

Of course, you always have the option to fork and/or make a pull request.

**Comment by ksurl** [comment]
I guess for now I can just add the ones I need to protected list for now. probably not worth rewriting the logic for the whole script. thanks for taking it into consideration. please close the issue

**Comment by aysiu** [comment]
Thanks, @ksurl. I'm not opposed to the idea if there seems to be a compelling use case, but I want to make sure that's the case before re-writing the whole logic.
